#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q8_KV, GGML_TYPE_Q8_KV);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q8_KV, GGML_TYPE_Q8_KV);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q8_KV, GGML_TYPE_Q8_KV);
DECL_FATTN_VEC_CASE(512, GGML_TYPE_Q8_KV, GGML_TYPE_Q8_KV);
