const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const elements = new Map();
const $ = id => {
  if (!elements.has(id)) elements.set(id, {innerHTML: '', textContent: '', style: {setProperty() {}}});
  return elements.get(id);
};
const source = fs.readFileSync(`${__dirname}/app.js`, 'utf8');
const context = vm.createContext({$, value: (id, v) => $(id).textContent = v});
vm.runInContext(source.slice(source.indexOf('function drawChart'), source.indexOf('function render(data)')), context);
context.drawChart('chart', 'range', [{step: 0, loss: 1}, {step: 1, loss: 2}, {step: 10, loss: 3}], 'loss', 'red');
assert.match($('chart').innerHTML, /L60\.0,/);
context.drawComparisonChart('combined', 'range', [], [{step: 5, loss: 2}], 'loss', 'red', 'blue');
assert.match($('combined').innerHTML, /validation-point/);
context.drawComparisonChart('combined', 'range', [{step: 0, loss: 1}, {step: 10, loss: 2}], [{step: 5, loss: 2}], 'loss', 'red', 'blue');
assert.match($('combined').innerHTML, /cx="300\.0"/);
assert.doesNotMatch($('combined').innerHTML, /NaN|Infinity/);
context.drawChart('chart', 'range', [{step: 0, loss: 1}, {step: 1, loss: 2}, {step: 10, loss: 999}], 'loss', 'red', {start: 0, end: 2});
assert.match($('chart').innerHTML, /L300\.0,10\.0/);
assert.doesNotMatch($('range').innerHTML, /999/);
context.drawComparisonChart('combined', 'range', [{step: 0, loss: 1}, {step: 1, loss: 2}], [{step: 1, loss: 2}, {step: 10, loss: 999}], 'loss', 'red', 'blue', {start: 0, end: 2});
assert.match($('combined').innerHTML, /cx="300\.0" cy="10\.0"/);
assert.doesNotMatch($('range').innerHTML, /999/);
context.drawChart('chart', 'range', [{step: 0, loss: 1}, {step: 0.25, loss: 2}], 'loss', 'red', {start: 0, end: 0.5});
assert.match($('chart').innerHTML, /L300\.0,10\.0/);
context.drawChart('single', 'range', [{step: 0, loss: 2}], 'loss', 'red', {start: 0, end: 5});
assert.doesNotMatch($('single').innerHTML, /class="area"/);
assert.doesNotMatch($('single').innerHTML, /class="line"/);
assert.match($('single').innerHTML, /class="point"/);
console.log('Chart coordinates and observed domains passed');
